<?php $this->layout('heritage/appHeritage') ?>

<?php $this->start('header') ?>
  <?= $this->insert('overall/apptopmenu',['top'=>$menuTop]) ?>
   
<?php $this->stop() ?>
 
<?php $this->start('container') ?>
   <div class="container">
   	  <div class="row">
   	  	<div class="col-xs-12">
   	  		<img src="views/assets/images/sambo.png" class="img-responsive">
   	  	</div>
   	  </div>
   </div>
<?php $this->stop() ?>