
<?php $this->layout('heritage/appHeritage',['osearch'=>$osearch]) ?>

<?php $this->start('header') ?>
  <?= $this->insert('overall/apptopmenu',['top'=>$menuTop]) ?>
<?php $this->stop() ?>

   
<?php $this->start('container') ?>
   
  <div class="row bg-img" id="content-data">
    <div class="col-xs-12">
    <div class="panel panel-default">
        <div class="panel-body" style="background-color: transparent;">
          
        
      
            <div class="col-xs-12">
                <center>
                     <br>
                     <h1 style="font-size: 50px;">Welcome to the family PlayGround.</h1>
                     <h4 style="width: 60%">Enjoy full access to all our unlimited services for 3 months, meet people, make friends, find the love of your life, or let something happen casually. what are you waiting?.Let the cosmos guide you and mark your own destiny.</h4>
                     <figure>
                       <img src="views/assets/images/logo2.png" class="img-responsive" width="100">
                     </figure>
                </center><br><br>
            </div>
            <div class="clearfix"></div>
              <div class="col-xs-12" style="background-color: #d8524f;height: auto;border-radius:5px;color:white;padding-bottom: 20px;overflow: hidden;">
                <div class="col-xs-2 text-center"> <div class="img-circle text-center jc-circle-80"><i class="fa fa-picture-o fa-2x"></i></div>Photos <br>Unlimited</div>
                <div class="col-xs-2 text-center"> <div class="img-circle text-center jc-circle-80"><i class="fa fa-comments-o fa-2x"></i></div> Messages <br>Unlimited</div>
                <div class="col-xs-2 text-center"><div class="img-circle text-center jc-circle-80"><i class="fa fa-users fa-2x"></i></div> Friendchat <br>Unlimited</div>
                <div class="col-xs-2 text-center"><div class="img-circle text-center jc-circle-80"><i class="fa fa-star fa-2x"></i></div> Favorites <br>Unlimited</div>
                <div class="col-xs-2 text-center"><div class="img-circle text-center jc-circle-80"><i class="fa fa-heart fa-2x"></i></div> Test Matching <br>Unlimited</div>
                <div class="col-xs-2 text-center"><div class="img-circle text-center jc-circle-80"><i class="fa fa-clock-o fa-2x"></i></div> Time <br> 3 Monhts</div>
                <div class="col-xs-12"><br><br><center><button class="btn btn-default btn-lg" id="jc-fullPackOn"><i class="fa fa-check-circle fa-lg"></i> Account Confirmation</button></center></div>
              </div>

      </div>
    </div>
  </div>
  </div>


<?php $this->stop() ?>

<?php $this->start('scripts') ?>
  <!-- Magnific Popup core JS file -->
  <script src="views/app/js/plans.js?<?= time()  ?>"></script>
<?php $this->stop() ?>