<br>
<ul style="list-style: none;padding: margin:0;margin-left:-45px;">
  <li class="text-center barleft-li"><a href="home"><i class="grey fa fa-dashcube fa-2x" aria-hidden="true"></i></a></li>
  <li class="text-center barleft-li"><a href="info/<?= $_SESSION[SESS_APP_ID]['u_id'] ?>"><i class="grey fa fa-user fa-2x" aria-hidden="true"></i></a></li>
  <li class="text-center barleft-li"><a href="photos/<?= $_SESSION[SESS_APP_ID]['u_id'] ?>"><i class="grey fa fa-camera fa-2x" aria-hidden="true"></i></a></li>
  <li class="text-center barleft-li"><a href="favorites"><i class="grey fa fa-heart fa-2x" aria-hidden="true"></i></a></li>
  <li class="text-center barleft-li"><a href="search"><i class="grey fa fa-search fa-2x" aria-hidden="true"></i></a></li>
  <li class="text-center barleft-li"><a href="setup"><i class="grey fa fa-cogs fa-2x" aria-hidden="true"></i></a></li>
</ul>