    <div class="col-xs-12" style="padding: 0px;">
      <br>
      <div class="panel panel-default shadow-grall" >
          <div class="panel-heading" style="background-color: #04d1cd !important;color:white;font-weight: bold">MY SEARCH OPTIONS <i class="fa fa-cog j-cursor pull-right" aria-hidden="true" id="jcode-left-osearch"></i></div>
          <div class="panel-body black" style="padding: 3px;height: 50%">
                   <?php
                     switch($osearch['preference']){
                        case 'with a woman':
                          $iconOption ='<i class="c-green-b font-xs fa fa-male""></i>';  
                        break;
                        case 'With a man':
                          $iconOption ='<i class="c-green-b font-xs fa fa-female""></i>';
                        break;
                        case 'with both':
                           $iconOption ='<i class="c-green-b font-xs fa fa-male""></i> <i class="c-green-b font-xs fa fa-female""></i>';  
                        break;
                      }
                   ?> 
                  <div id="jcode-osearch-static"> 
                       <table class="table table-condensed">
                         <tr><td class="text-center no-border"><i class="yellowb font-xs fa fa-search" aria-hidden="true"></i></td><td class="no-border"> <?= $osearch['option'] ?></td></tr>
                         <tr><td class="text-center no-border"><?= $iconOption ?></td><td class="no-border"><?= $osearch['preference'] ?></td></tr>
                         <tr><td class="text-center no-border"><i class="yellowb font-xs fa fa-circle-o-notch" aria-hidden="true"></i></td><td class="no-border"> Intro <?= $osearch['redad0'] ?> and <?= $osearch['redad1'] ?> Ages</td></tr>
                         <tr><td class="text-center no-border"><i class="yellowb font-xs fa fa-balance-scale" aria-hidden="true"></i></td><td class="no-border"> <?= $osearch['signo'] ?></td></tr>
                         <tr><td class="text-center no-border"><i class="yellowb font-xs fa fa-map-marker" aria-hidden="true"></i></td><td class="no-border"> <?= $osearch['pb_state'] ?></td></tr>
                         <tr><td class="text-center no-border"><i class="yellowb font-xs fa fa-street-view" aria-hidden="true"></i></td><td class="no-border"> <?= $osearch['pb_city'] ?></td></tr>
                       </table>
                   </div>
         </div>
      </div>

      <div class="panel panel-default shadow-grall">
          <div class="panel-heading" style="background-color: #04d1cd !important;color:white;font-weight: bold">CHAT</div>
          <div class="panel-body black" style="padding: 3px;">
             <div id="jcode-load-chat" data-conextifly="cxtfly<?= $_SESSION[SESS_APP_ID]['u_id']?>"  style="height: 70%;width: 100%;overflow-y: auto;">

             </div>
          </div>
        </div>

    </div>
    <div class="clearfix"></div>
   