              <div class="panel panel-default shadow-grall hidden" style="margin-bottom:0px;" id="ch_panel">
                <div class="panel-heading" style="background-color: #fff !important;">
                       <ul class="h-menu">
                         <li class="h-menu-li"><i class="fa fa-circle c-green-b" aria-hidden="true"></i></li>
                         <li class="h-menu-li" id="ch_name"><a href="profile/" class="jc-a"><b id="ch_name"></b></a></li>
                         <li class="h-menu-li pull-right"><i class=" fa fa-times fa-lg jcode-chat-remove j-cursor"></i></li>
                       </ul>
                </div>
                <div class="panel-body" id="pone_sms" style="background-color:#eee;width:100%;height:250px;overflow-y:auto">
            
                </div>
                <div class="panel-footer" style="padding:0px;">
                    <div style="height:12px;position:absolute;margin-top:-20px;margin-left:20px;font-size:14px;" class="pull-left hide"><b>Writing ...</b></div>
                    <textarea placeholder="write a message" id="ch_text" style="width:100%;border:none;padding:10px;overflow: hidden;"></textarea>
                </div>
              </div>