<div class="modal fade" tabindex="-1" role="dialog" id="modal_favoritos">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: #ecf1f5;">
      <div class="modal-header b-red white">
        <i data-dismiss="modal" class="fa fa-times-circle  red pull-right fa-2x cursor" aria-hidden="true"></i>
        <h4 class="modal-title"><i class="fa fa-heart" aria-hidden="true"></i> FAVORITE</h4>
      </div>
      <div class="modal-body">
        <!--body init-->
        <div class="row">
            <div class="col-md-12" id="pone_favoritos" style="overflow-y: auto;height: 500px;">

            </div>  
         </div>
        <!--body end -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
