<div class="modal fade" tabindex="-1" role="dialog" id="modal_notifications">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: #ecf1f5;">
      <div class="modal-header b-yellowa white">
        <i data-dismiss="modal" class="fa fa-times-circle  red pull-right fa-2x cursor" aria-hidden="true"></i>
        <h4 class="modal-title"><i class="fa fa-bell" aria-hidden="true"></i> NOTIFICATIONS</h4>
      </div>
      <div class="modal-body">
        <!--body init-->
        <div class="row">
            <div class="col-md-12" id="pone_notifications" style="overflow-y: auto;height: 500px;">

            </div>  
         </div>
        <!--body end -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
