    <!-- SLIDER EXAMPLE -->
            <div id="rev_slider_211_1_wrapper" class="hiddex-xs rev_slider_wrapper fullwidthbanner-container" data-alias="webproductlighthero" style="background-color:transparent;margin:0 auto;padding:0;margin-bottom:0px;">
                <!-- START REVOLUTION SLIDER 5.1.1RC fullwidth mode -->
                <div id="rev_slider_211_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.1.1RC">
                    <ul>
                        <!-- SLIDE DE DIA  -->
                        <li data-index="rs-699" data-transition="parallaxvertical" data-slotamount="default" data-easein="Bounce.easeIn" data-easeout="default" data-masterspeed="2000" data-rotate="0" data-saveperformance="off" data-title="TheplayGround" data-description="" style="background-image:url(views/assets/images/1-fonado.png);background-position: 50% 50%;background-repeat: no-repeat;background-size: cover;" data-thumb="views/assets/images/slide0.jpg" >
                            <img src="views/assets/images/tomaOne/1-fondo.png"  alt=""   width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"  data-no-retina>
                            <!-- LAYERS -->
                            <!-- SOL -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-6" 
                                 id="slide-699-layer-1" 
                                 data-x="['center','center','center','right']" 
                                 data-hoffset="['0','0','0','0']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['30','30','30','30']" 
                                 data-width="none" 
                                 data-height="none" 
                                 
                                 data-transform_idle="o:0.5;" 
                                 data-transform_in="x:top;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="2000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 4;">


                                 <img src="views/assets/images/tomaOne/4-sol.png" alt="" 
                                  width="93"
                                  height="94" 
                                  data-ww="['93px','93px','93px','93px']" 
                                  data-hh="['94px','94px','94px','94px']" data-no-retina>



                            </div>
                            <!-- EDIFICIOS -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-6" 
                                 id="slide-699-layer-1" 
                                 data-x="['center','center','center','center']" 
                                 data-hoffset="['0','0','0','0']" 
                                 data-y="['middle','middle','middle','bottom']" 
                                 data-voffset="['30','50','25','25']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="y:bottom;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="5000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 5;">
                                 <img src="views/assets/images/tomaOne/5-edificios.png" alt="" width="1200" height="726" 
                                      data-ww="['1000px','1000px','800px','500px']" 
                                      data-hh="['800','600px','700px','350px']" 
                                      data-no-retina>
                            </div>



                            <!-- NUBES-FRONTALES -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-5" 
                                 id="slide-699-layer-12" 
                                 data-x="['center','center','center','center']" 
                                 data-hoffset="['143','143','20','20']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['57','55','20','20']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="opacity:0;s:300;e:Power2.easeInOut;" 
                                 data-transform_out="opacity:0;s:300;s:300;" 
                                 data-start="4000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 8;">
                                <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" 
                                       data-speed="50" data-xs="-300" 
                                       data-xe="300" data-ys="0" data-ye="0">
                                       <img src="views/assets/images/tomaOne/2-nubes.png" alt="" width="1115" 
                                             height="176" 
                                             data-ww="['1115px','1000px','600','500px']" 
                                             data-hh="['176px','80px','70','60px']" 
                                             data-no-retina>
                                </div>
                            </div>

                            <!-- PLANTAS -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-4" 
                                 id="slide-699-layer-3" 
                                 data-x="['center','center','center','center']" 
                                 data-hoffset="['0','0','0','0']" 
                                 data-y="['bottom','bottom','bottom','bottom']" 
                                 data-voffset="['80','80','80','80']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="o:0;s:1000" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="3500" 
                                 data-responsive_offset="on" 
                                 style="z-index: 8;">
                                 <img src="views/assets/images/tomaOne/6-plantas.png" alt="" width="1000" height="400" 
                                      data-ww="['1000px','1000px','500px','400px']" 
                                      data-hh="['400px','400px','300px','200px']" 
                                      data-no-retina>
                            </div>
                            <!-- PISO-VERDE -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['center','center','center','center']" 
                                 data-hoffset="['0','0','0','0']" 
                                 data-y="['bottom','bottom','bottom','bottom']" 
                                 data-voffset="['-100','-100','-110','-100']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="y:bottom;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="1000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 11;">
                                 <img src="views/assets/images/tomaOne/7-piso.jpg" alt="" width="1980" height="241" 
                                 data-ww="['1980px','1200px','1000px','500px']" 
                                 data-hh="['241px','241px','241px','200px']" 
                                 data-no-retina>
                            </div>

                            <!-- BANCAS-BLANCAS -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['center','center','center','right']" 
                                 data-hoffset="['0','0','0','-1000']" 
                                 data-y="['bottom','bottom','bottom','bottom']" 
                                 data-voffset="['130','130','120','90']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="x:right;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="2000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 12;">
                                 <img src="views/assets/images/tomaOne/8-bancas.png" alt="" width="772" height="149" 
                                 data-ww="['772px','260px','672px','250px']" 
                                 data-hh="['149px','450px','120px','70px']" 
                                 data-no-retina>
                            </div>

                            <!-- /.........................CHAT....................-/ -->
                            
                            <!--EL -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['left','left','left','left']" 
                                 data-hoffset="['400','396','100','-30']" 
                                 data-y="['bottom','bottom','bottom','bottom']" 
                                 data-voffset="['110','110','110','-150']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="o:0;s:1000" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="3000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/9-el.png" alt="" 
                                       width="139" height="305" 
                                       data-ww="['139px','260px','130px','200px']" 
                                       data-hh="['305px','450px','225px','400px']" 
                                       data-no-retina>
                            </div>
                            <!--CHAT-HOLA-EL -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['right','right','right','right']" 
                                 data-hoffset="['220','120','120','0']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['350','350','550','325']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="6000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/1-sms-el.png" alt="" 
                                      width="125" height="60" 
                                      data-ww="[182px','182px','162px','182px']" 
                                      data-hh="['109px','109px','86px','109px']"
                                       data-no-retina>
                            </div>
                            <!--CHAT-HOLA-ELLA -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['left','left','left','left']" 
                                 data-hoffset="['240','240','127','0']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['350','297','550','380']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="7500" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/1-sms-ella.png" alt="" 
                                       width="115" height="60" 
                                       data-ww="['183px','162px','162px','183px']" 
                                       data-hh="['108px','86px','86px','108px']" 
                                       data-no-retina>
                            </div>
                            <!--CHAT-2-EL -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['right','right','right','right']" 
                                 data-hoffset="['220','220','100','0']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['240','280','450','230']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="8500" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/2-sms-el.png" alt="" 
                                 width="132" height="60" 
                                 data-ww="['210px','210px','210px','217px']" 
                                 data-hh="['92px','92px','92px','108px']" 
                                 data-no-retina>
                            </div>
                            <!--CHAT-2-ELLA -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['left','left','left','left']" 
                                 data-hoffset="['240','240','127','-30']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['230','300','450','280']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="s:1500;e:Power3.easeOut;" 
                                 data-transform_out="e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="9500" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/2-sms-ella.png" alt="" 
                                 width="132" height="60" 
                                 data-ww="['183px','183px','162px','183px']" 
                                 data-hh="['108px','108px','83px','108px']" 
                                 data-no-retina>
                            </div>
                            <!--CHAT-EL-CENAMOS -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['right','right','right','right']" 
                                 data-hoffset="['220','220','100','0']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['90','297','300','100']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="12000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/3-sms-el.png" alt="" 
                                       width="217" height="109" 
                                       data-ww="['273px','273px','273px','273px']" 
                                       data-hh="['135px','135px','135px','135px']" 
                                       data-no-retina>
                            </div>
                            <!--CHAT-ELLA-SI -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['left','left','left','left']" 
                                 data-hoffset="['240','240','127','-20']" 
                                 data-y="['top','top','top','top']" 
                                 data-voffset="['100','297','300','150']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="13000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/3-sms-ella.png" alt="" 
                                       width="217" height="109" 
                                       data-ww="['183px','183px','162px','183px']" 
                                       data-hh="['108px','108px','83px','108px']" 
                                       data-no-retina>
                            </div>
                            <!-- /.........................CHAT....................-/ -->

                            <!--ELLA -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['right','right','right','right']" 
                                 data-hoffset="['410','400','100','-60']" 
                                 data-y="['bottom','bottom','bottom','bottom']" 
                                 data-voffset="['110','110','110','-200']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="3000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaOne/10-ella.png" alt="" width="117" height="304" 
                                       data-ww="['117px','260px','130px','300px']" 
                                       data-hh="['305px','450px','225px','500px']" 
                                       data-no-retina>
                            </div> 
                        </li>

                        <!-- SLIDE DE NOCHE  -->
                        <li data-index="rs-700" data-transition="parallaxvertical" data-slotamount="default" data-easein="Bounce.easeIn" data-easeout="default" data-masterspeed="2000" data-rotate="0" data-saveperformance="off" data-title="TheplayGround" data-description=""  data-thumb="views/assets/images/slide1.jpg" >
                            
                            <!-- ESTRELLAS -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-6" 
                                 id="slide-699-layer-1" 
                                 data-x="['center','right','center','center']" 
                                 data-hoffset="['0','-453','70','60']" 
                                 data-y="['top','middle','middle','bottom']" 
                                 data-voffset="['30','50','211','25']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="x:right;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="1500" 
                                 data-responsive_offset="on" 
                                 style="z-index: 4;">
                                 <img src="views/assets/images/tomaDos/2-estrellas.png" alt="" width="1000" height="900" data-ww="['1000px','900px','500px','350px']" data-hh="['900','600px','300px','210px']" data-no-retina>
                            </div>
                            <!-- LUNA -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-6" 
                                 id="slide-699-layer-1" 
                                 data-x="['right','right','center','center']" 
                                 data-hoffset="['0','-453','70','60']" 
                                 data-y="['bottom','middle','middle','bottom']" 
                                 data-voffset="['230','50','211','25']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="y:bottom;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="3600" 
                                 data-responsive_offset="on" 
                                 style="z-index: 5;">
                                 <img src="views/assets/images/tomaDos/7-luna.png" alt="" width="588" height="491" data-ww="['588px','491px','500px','350px']" data-hh="['491','600px','300px','210px']" data-no-retina>
                            </div>
                            <!-- EDIFICIOS -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-6" 
                                 id="slide-699-layer-1" 
                                 data-x="['center','right','center','center']" 
                                 data-hoffset="['0','-453','70','60']" 
                                 data-y="['middle','middle','middle','bottom']" 
                                 data-voffset="['30','50','211','25']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="y:bottom;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="2000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 6;">
                                 <img src="views/assets/images/tomaDos/3-edificios.png" alt="" width="1200" height="726" data-ww="['1200px','1000px','500px','350px']" data-hh="['726','600px','300px','210px']" data-no-retina>
                            </div>


                            <!-- BALCON -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-4" 
                                 id="slide-699-layer-3" 
                                 data-x="['center','left','center','center']" 
                                 data-hoffset="['0','633','-110','-60']" 
                                 data-y="['bottom','top','top','bottom']" 
                                 data-voffset="['0','203','590','20']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="y:bottom;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="2500" 
                                 data-responsive_offset="on" 
                                 style="z-index: 8;">
                                 <img src="views/assets/images/tomaDos/4-balcon.png" alt="" width="1980" height="161" data-ww="['1980px','430px','200px','170px']" data-hh="['161px','540px','251px','213px']" data-no-retina>
                            </div>


                            <!-- MESA -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['center','left','left','left']" 
                                 data-hoffset="['0','553','127','58']" 
                                 data-y="['bottom','top','top','top']" 
                                 data-voffset="['0','297','622','529']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="y:bottom;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="3000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 11;">
                                 <img src="views/assets/images/tomaDos/5-silla-y-mesa.png" alt="" width="578" height="225" data-ww="['578px','260px','130px','100px']" data-hh="['225px','450px','225px','173px']" data-no-retina>
                            </div>
                            <!--CHATS-->
                             <!-- 1-sms-el -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['right','left','left','left']" 
                                 data-hoffset="['500','553','127','58']" 
                                 data-y="['center','top','top','top']" 
                                 data-voffset="['-100','297','622','529']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="4000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaDos/1-sms-el.png" alt="" width="125" height="60" data-ww="[182px','260px','130px','100px']" data-hh="['109px','450px','225px','173px']" data-no-retina>
                            </div>
                            <!-- 1-sms-el -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['left','left','left','left']" 
                                 data-hoffset="['500','553','127','58']" 
                                 data-y="['center','top','top','top']" 
                                 data-voffset="['-100','297','622','529']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="6000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 13;">
                                 <img src="views/assets/images/tomaDos/1-sms-ella.png" alt="" width="125" height="60" data-ww="[182px','260px','130px','100px']" data-hh="['109px','450px','225px','173px']" data-no-retina>
                            </div>
                            <!--CHATS-->

                            <!--BRILLO-->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['center','left','left','left']" 
                                 data-hoffset="['0','553','127','58']" 
                                 data-y="['center','top','top','top']" 
                                 data-voffset="['0','297','622','529']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:0.5;" 
                                 data-transform_in="rY:40px;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="6000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 7;">
                                 <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed="30" data-xs="0" data-xe="600" data-ys="0" data-ye="0"><img src="views/assets/images/tomaDos/8-destello.png" alt="" width="553" height="619" data-ww="['553px','619px','250','125px']" data-hh="['619px','273px','137','68px']" data-no-retina>
                                </div>
                                 
                            </div>
                            <!-- PAREJA -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" 
                                 id="slide-699-layer-5" 
                                 data-x="['center','left','left','left']" 
                                 data-hoffset="['0','553','127','58']" 
                                 data-y="['bottom','top','top','top']" 
                                 data-voffset="['-40','297','622','529']" 
                                 data-width="none" 
                                 data-height="none" 
                                 data-whitespace="nowrap" 
                                 data-transform_idle="o:1;" 
                                 data-transform_in="x:right;s:1500;e:Power3.easeOut;" 
                                 data-transform_out="opacity:0;s:1500;e:Power4.easeIn;s:1500;e:Power4.easeIn;" 
                                 data-start="3000" 
                                 data-responsive_offset="on" 
                                 style="z-index: 12;">
                                 <img src="views/assets/images/tomaDos/6-pareja.png" alt="" width="572" height="480" data-ww="['572px','260px','130px','100px']" data-hh="['480px','450px','225px','173px']" data-no-retina>
                            </div>
                            <img src="views/assets/images/tomaDos/1-fondo.png"  alt=""  width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg">
                        </li>
                    </ul>
                    <div class="tp-bannertimer tp-bottom" style="height: 7px; background-color: rgba(255, 255, 255, 0.25);"></div>
                </div>
            </div>

            <!-- END REVOLUTION SLIDER -->
            <script type="text/javascript">
                var tpj = jQuery;

                var revapi211;
                tpj(document).ready(function() {
                    if (tpj("#rev_slider_211_1").revolution == undefined) {
                        revslider_showDoubleJqueryError("#rev_slider_211_1");
                    } else {
                        revapi211 = tpj("#rev_slider_211_1").show().revolution({
                            sliderType: "standard",
                            jsFileLocation: "views/revolution/",
                            sliderLayout: "fullwidth",
                            dottedOverlay: "none",
                            delay: 15000,
                            navigation: {
                                    keyboardNavigation:"on",
                                    keyboard_direction: "horizontal",
                                    mouseScrollNavigation:"off",
                                    onHoverStop:"off",
                                    touch:{
                                        touchenabled:"on",
                                        swipe_threshold: 75,
                                        swipe_min_touches: 1,
                                        swipe_direction: "horizontal",
                                        drag_block_vertical: false
                                    }
                                    ,
                                    arrows: {
                                        style:"zeus",
                                        enable:true,
                                        hide_onmobile:true,
                                        hide_under:600,
                                        hide_onleave:true,
                                        hide_delay:200,
                                        hide_delay_mobile:1200,
                                        tmp:'<div class="tp-title-wrap">    <div class="tp-arr-imgholder"></div> </div>',
                                        left: {
                                            h_align:"left",
                                            v_align:"center",
                                            h_offset:30,
                                            v_offset:0
                                        },
                                        right: {
                                            h_align:"right",
                                            v_align:"center",
                                            h_offset:30,
                                            v_offset:0
                                        }
                                    }
                                    ,
                                    //bullets: {
                                        enable:true,
                                        hide_onmobile:true,
                                        hide_under:600,
                                        style:"metis",
                                        hide_onleave:true,
                                        hide_delay:200,
                                        hide_delay_mobile:1200,
                                        direction:"horizontal",
                                        h_align:"center",
                                        v_align:"bottom",
                                        h_offset:0,
                                        v_offset:30,
                                        space:5,
                                        tmp:'<span class="tp-bullet-img-wrap">  <span class="tp-bullet-image"></span></span><span class="tp-bullet-title">{{title}}</span>'
                                    //}
                                },
                            shadow:0,
                            responsiveLevels: [1240, 1024, 778, 480],
                            visibilityLevels: [1240, 1024, 778, 480],
                            gridwidth: [1400, 1240, 778, 480],
                            gridheight: [768, 768, 960, 720],
                            lazyType: "none",
                            parallax: {
                                type: "none",
                                origo: "slidercenter",
                                speed: 800,
                                levels: [5, 10, 15, 20, 25, 30, 5, 0, 45, 50, 47, 48, 49, 50, 51, 55],
                               
                                ddd_shadow: "off",
                                ddd_bgfreeze: "off",
                                ddd_overflow: "hidden",
                                ddd_layer_overflow: "visible",
                                ddd_z_correction: 65,
                            },
                            spinner: "off",
                            autoHeight: "off",
                            disableProgressBar: "on",
                            hideThumbsOnMobile: "off",
                            hideSliderAtLimit: 0,
                            hideCaptionAtLimit: 0,
                            hideAllCaptionAtLilmit: 0,
                            debugMode: false,
                            fallbacks: {
                                simplifyAll: "off",
                                disableFocusListener: false,
                            }
                        });
                    }
                }); /*ready*/
            </script>

   