<div class="nav" id="top-menu shadow-intense" style="background-color: #111111;color:white;padding:10px;">
	<div class="container-fluid">
		<div class="row">
		    <div class="col-xs-2 col-lg-8">
		      <div class="pull-left">
		        <center>	
		         <a href="home" ><img style="margin-top: 4px;" src="views/assets/images/logo.png" width="35" class="img-reponsive"></a> <span class="hidden-xs"><b>PLAYGROUND</b></span>
		        </center>
		      </div>
		    </div>
			<div class="col-xs-10 col-lg-4">
					<ul class="h-menu h-menu-li pull-right">
						<li><a id="jcode-login-intro" class="btn btn-default white" rel="loginpopover" style="background-color: #5b5a59;color:white">Login</a></li>
					    <li><a id="jcode-top-creates" class="btn btn-default white" rel="regpopover" style="background-color: #741b09;color:white">Create account</a></li>
					</ul>
			</div>
		</div>
	</div>
</div>