
<?php $this->layout('heritage/heritage') ?>
<?php $this->start('container') ?>
<section style="background-color: #373740;width: 100%;height: 650px;">
  <div class="container">	
	<div class="row"><br><br><br><br><br><br>
		<div class="col-xs-12 col-md-6">
			<h1 style="font-size:54px;color: #f4ffa5;"><b>SORRY!</b></h1>
			<h2 style="color:white;font-size: 34px;">BUT I CAN'T DO IT</h2>
            <p style="color:white;">The page you are looking for was moved, removed, renamed or might never existed.</p>
		    <br>
		    <a href="home" class="btn btn-default btn-lg" style="background-color: #e56e54;color:white">GO HOME</a>
		</div>
		<div class="col-xs-12 col-md-6">
			<figure>
				<img src="views/app/images/404.gif" alt="">
			</figure>
		</div>
	</div>
  </div>
</section>
<?php $this->stop() ?>

